services:
  app:
    user: "${USER_ID}" # Set the user for the container using the USER_ID environment variable
    hostname: "${HOST_NAME}" # Set the hostname for the container using the HOST_NAME environment variable
    image: picpay-docker-image:latest # Specify the Docker image to use for the service
    platform: linux/amd64 # Set the platform to ensure compatibility with linux/amd64 architecture
    container_name: picpay-container     # Name the container 'picpay-container'
    # Build configuration for the image
    build:
      context: . # Set the build context to the current directory
      dockerfile: ./docker/Dockerfile # Specify the Dockerfile location
      # Pass build-time arguments for the Dockerfile
      args:
        USER_NAME: "${USER_NAME}"  # User name passed as an argument to the Dockerfile
        USER_ID: "${USER_ID}"  # User ID passed as an argument to the Dockerfile
    # Define environment variables to be used by the container
    environment:
      MODEL_TYPE: "${MODEL_TYPE:-pyspark}"  
    # Mount the volumes inside the container
    volumes:
      - ./src/:/app/src/
      - ./tests/:/app/tests/
      - ./models/:/app/models/
    # Map the host port 8080 to the container port 8080
    ports:
      - 8080:8080
    ipc: host # Set the inter-process communication mode to host, enabling shared memory access
    init: true # Ensure that the container's init system is started

